- client/src/App.tsx
- client/src/components/Sidebar.tsx
- client/src/components/Tabs.tsx
- client/src/components/ToolRunCard.tsx
- client/src/components/ToolsTab.tsx
- client/src/examples/requestExample.ts
- client/src/lib/requestTypes.ts
- client/src/utils/requestStorage.ts
- client/src/utils/requestUtils.ts
- client/src/utils/schemaUtils.ts
> Save requests

- client/src/components/ListPane.tsx
- client/src/components/PromptsTab.tsx
- client/src/components/ResourcesTab.tsx
- client/src/components/ToolsTab.tsx
> fix resources

- package.json
- server/src/index.ts
> dynamically choose a port

- client/src/App.tsx
- client/src/components/ClientFormSection.tsx
- client/src/components/ConfigImportDialog.tsx
- client/src/components/ConnectionSection.tsx
- client/src/utils/configImportUtils.ts
Supports single and multi import
> Import via json

- client/src/components/ActivityTab.tsx
- client/src/components/History.tsx
- client/src/components/RequestHistoryItem.tsx
- client/src/components/ResultsTab.tsx
- client/src/components/TabbedHistoryPanel.tsx
- client/src/components/ToolResult.tsx
- client/src/hooks/useMCPOperations.ts
* Adds timestamps
* Adds latency
* Distinguishes which server the requests come
> Activity refactor

- client/src/App.tsx
- client/src/components/ActivityTab.tsx
- client/src/components/ClientLogsTab.tsx
- client/src/components/History.tsx
- client/src/components/TabbedHistoryPanel.tsx
- client/src/hooks/helpers/types.ts
- client/src/hooks/useConnectionState.ts
- client/src/hooks/useMCPOperations.ts
- client/src/mcpjamAgent.ts
- client/src/mcpjamClient.ts
We log all logs you'd typically see in the Chrome console into the app itself.
> Log everything 1

- client/src/App.tsx
Summary
This pull request addresses a bug where existing server connections were terminated after completing an OAuth flow for a new server. The root cause was a full application reload on the OAuth callback, which reset the connection agent. The initial fix attempted to reconnect all servers but was bypassed by a useEffect hook that restored them in a disconnected state. Additionally, a UI synchronization issue prevented the connection status from updating correctly.
Changes
Prevents Agent Restoration During OAuth: The useEffect hook that restores the agent is now disabled during the OAuth callback, ensuring the connection logic runs correctly.
Reconnects All Servers: After the OAuth redirect, the connection logic now re-initializes the agent and reconnects to all previously configured …
> Don't reload after Oauth

- .github/workflows/main.yml
- .github/workflows/publish-docker.yml
- client/src/components/AuthDebugger.tsx
- client/src/components/ConfigImportDialog.tsx
- client/src/components/ConnectionSection.tsx
- client/src/components/RequestHistoryItem.tsx
- client/src/components/ResultsTab.tsx
- client/src/components/ToolResult.tsx
- client/src/components/ToolsTab.tsx
- client/src/examples/requestExample.ts
- client/src/lib/serverTypes.ts
- client/src/utils/configImportUtils.ts
- client/src/utils/configUtils.ts
- package.json
- server/src/index.ts
> npx prettier --write .

- README.md
- client/src/hooks/useConnectionState.ts
- client/src/mcpjamAgent.ts
- client/src/mcpjamClient.ts
> Fix timeout config

- server/src/mcpProxy.ts
@nabuskey i saw your issue in the inspector repo and i'm adding your suggestions here!
> Add better msg for server errors

- client/src/components/ToolRunCard.tsx
Based on the suggestion @andraz made in the inspector repo. When user has a JSON object e.g`{"opt_fields": "hello", "limit": 1}` in their clipboard, we allow them to paste it directly:
> Paste input to tool params

- client/src/components/History.tsx
- client/src/lib/hooks/useDraggablePane.ts
> Enhance history slider

- client/src/components/chat/MessageBubble.tsx
- client/src/lib/chatLoop.ts
- client/src/utils/toolCallHelpers.ts
---
name: Pull Request
about: Create a pull request to help us improve
title: ""
labels: ""
assignees: ""
---
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
_A brief description of the motivation behind this PR. Link to any related issues._
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
_If your change is a breaking change, please describe the impact and migration path for existing users._
_Add any other context about the problem here._
> Fix chat regex detection 

- client/src/App.tsx
- client/src/components/ClientFormSection.tsx
- client/src/components/Sidebar.tsx
---
name: Pull Request
about: Create a pull request to help us improve
title: ""
labels: ""
assignees: ""
---
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
_A brief description of the motivation behind this PR. Link to any related issues._
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
_If your change is a breaking change, please describe the impact and migration path for existing users._
_Add any other context about the problem here._
> change wordage

- client/src/App.tsx
- client/src/hooks/app/useAppEffects.ts
- client/src/hooks/app/useLocalStoragePersistence.ts
- client/src/hooks/app/useOAuthHandlers.ts
- client/src/hooks/app/useServerManagement.ts
- client/src/services/mcpRequestService.ts
- client/src/utils/renderHelpers.tsx
I refactored App.tsx. Create new hooks and components.
> Refactor App.tsx

- client/src/components/chat/Chat.tsx
- client/src/components/chat/EmptyChatsState.tsx
- client/src/components/chat/OllamaSetupGuide.tsx
- client/src/lib/providers/ollamaProvider.ts
- package-lock.json
- package.json
---
name: Pull Request
about: Create a pull request to help us improve
title: ""
labels: ""
assignees: ""
---
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
_A brief description of the motivation behind this PR. Link to any related issues._
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
_If your change is a breaking change, please describe the impact and migration path for existing users._
_Add any other context about the problem here._
> improve ollama instructions

- client/index.html
- client/src/App.css
Copying from this commit in the original inspector
https://github.com/modelcontextprotocol/inspector/pull/581/files
> Full width

- client/src/components/ActivityTab.tsx
- client/src/components/ClientLogsTab.tsx
- client/src/components/TabbedHistoryPanel.tsx
Move tha trash icon from ActivityTab and clientLogsTab into TabbedHistoryPanel
Resolve: #147
> feat(client): Move trash to the top bar

- client/src/components/chat/ToolCallApproval.tsx
- client/src/components/chat/ToolSelector.tsx
Fix: Replaced the gear icon in the chat dropdown with a tool icon
> Fix: Replaced the gear icon in the chat dropdown with a tool icon 

- .github/PULL_REQUEST_TEMPLATE.md
- client/src/components/History.tsx
- client/src/components/RequestHistoryItem.tsx
- client/src/components/TabbedHistoryPanel.tsx
- client/src/components/chat/Chat.tsx
- client/src/components/chat/ToolCallApproval.tsx
- package-lock.json
{
request: string;
response?: string;
timestamp: string;
latency?: number;
}
I have Replaced this with RequestHistoryInfo type.
and ran 
npm run test there was no issues
> Reuse types for RequestHistoryInfo #168

- README.md
Shows Docker pulls in the README
Fixes #182 
_Brief description of your changes_
> feat: Update README.md  with docker pulls

- server/src/shared/MCPProxyService.ts
- server/src/shared/TransportFactory.ts
- server/src/shared/types.ts
- server/src/shared/utils.ts
✅ Created Directory Structure
server/src/shared/
├── MCPProxyService.ts    (placeholder)
├── TransportFactory.ts   (placeholder)
├── types.ts             (complete)
└── utils.ts             (complete)
✅ Core Types Defined
- ServerConfig: Configuration for different transport types
- MCPProxyOptions: Options for the proxy service
- ConnectionStatus: Connection state tracking
- TransportFactoryOptions: Transport factory configuration
- Logger: Logging interface
✅ Utility Functions Created
- generateSessionId(): Creates unique session IDs
- validateServerConfig(): Validates server configurations
- ConsoleLogger: Default logger implementation
> Created the base infrastructure for the MCPProxyService extraction

- server/src/shared/TransportFactory.ts
Core Features Implemented:
1. Transport Creation: Factory method that creates STDIO, SSE, and StreamableHTTP transports
2. Header Management: Proper header passthrough for authenticated connections
3. Environment Handling: Merges default, process, and custom environment variables
4. Lifecycle Management: Timeout handling and event cleanup
5. Error Handling: Comprehensive logging and error propagation
Key Methods:
- createTransport(): Main factory method with config validation
- createStdioTransport(): Handles local process spawning
- createSSETransport(): Manages Server-Sent Events connections
- createStreamableHTTPTransport(): Handles HTTP streaming connections
- setupTransportLifecycle(): Common timeout and event management
Transport Factory Features:
- Header Passthrough: …
>  TransportFactory Implementation

- server/src/shared/MCPProxyService.ts
- server/src/shared/index.ts
Core MCPProxyService Features:
1. EventEmitter Integration: Emits connection/disconnection/error events for monitoring
2. Connection Management: Create, track, and close MCP server connections
3. Transport Access: Get backing server and web app transports by session ID
4. Status Tracking: Monitor connection states, error counts, and activity
5. Lifecycle Management: Automatic cleanup and event handling
Key Methods Implemented:
Connection Management:
- createConnection(): Create new MCP server connections with config validation
- closeConnection(): Clean shutdown of specific connections
- closeAllConnections(): Bulk connection cleanup
- getActiveConnections(): List all active session IDs
Transport Access:
- getTransport(): Get backing server transport by session ID
- getWebAppTransport(): …
> MCPProxyService Implementation

- server/src/database/DatabaseManager.ts
- server/src/index.ts
- server/src/shared/MCPProxyService.ts
- server/src/shared/TransportFactory.ts
- server/src/shared/index.ts
- server/src/shared/types.ts
Summary
- Extracted transport management logic from main server into reusable MCPProxyService
- Maintained full backward compatibility
- Fixed connection issues and improved cleanup handling
Changes
- Added: MCPProxyService class for centralized transport management
- Added: TransportFactory for creating different transport types
- Refactored: Main server routes to use MCPProxyService instead of inline transport logic
- Fixed: Duplicate cleanup logs during connection teardown
- Fixed: JSON parsing errors for shell command arguments
Technical Details
- Maintains support for all transport types (STDIO, SSE, StreamableHTTP)
- Preserves existing API endpoints and behavior
- Adds connection lifecycle management with proper cleanup guards
- Uses centralized logging and error handling
Testing
- …
> Use new MCPProxyService in the server

- client/src/App.tsx
- client/src/components/Sidebar/ConnectionItem.tsx
- client/src/components/Sidebar/Sidebar.tsx
- client/src/components/Sidebar/connectionHelpers.tsx
Create new sidebar component
NA
> New sidebar component

- server/src/test-server.ts
- server/src/testing/TestServer.ts
test-server.ts - Entry Point/Bootstrap
- Purpose: Main executable entry point
- Role: Application launcher and process manager
- Contains:
- Command-line argument parsing
- Environment setup
- Service initialization (Database, MCPProxyService)
- Port detection and server startup
- Process signal handling (SIGINT, SIGTERM)
- Graceful shutdown logic
- Error handling for startup failures
TestServer.ts - Core Implementation
- Purpose: HTTP server implementation and API routes
- Role: Express.js application with REST endpoints
- Contains:
- Express app configuration
- Middleware setup (CORS, body parsing, logging)
- All API route handlers (/api/test/*)
- Business logic for test execution
- Request/response handling
- Server start/stop methods
Relationship
test-server.ts (entry point)
↓ imports …
> Implement Test Server

- client/src/App.tsx
- client/src/components/ClientFormSection.tsx
- client/src/hooks/app/useServerManagement.ts
- client/src/hooks/useServerState.ts
- client/src/lib/utils/config/configHelpers.ts
_Brief description of your changes_
> fix streamable

- v1-0-0/src/app/api/mcp/chat/route.ts
- v1-0-0/src/app/api/oauth/discover/route.ts
- v1-0-0/src/app/page.tsx
- v1-0-0/src/components/ActiveServerSelector.tsx
- v1-0-0/src/components/connection/AddServerModal.tsx
- v1-0-0/src/components/mcp-sidebar.tsx
- v1-0-0/src/hooks/use-chat.ts
- v1-0-0/src/hooks/useAppState.ts
- v1-0-0/src/lib/oauth-registration.ts
_Brief description of your changes_
> Add option for no auth

- client/src/components/settings/ProviderCard.tsx
- package-lock.json
> Added left padding to the Model Settings

- v1-0-0/src/components/connection/AddServerModal.tsx
Solves Issue #275
Adds cursor pointer to "Add Variable " button
> feat(v1-0-0): Add cursor pointer to 'Add Variable' button

- v1-0-0/eslint.config.mjs
- v1-0-0/src/app/api/mcp/chat/route.ts
- v1-0-0/src/app/api/mcp/prompts/get/route.ts
- v1-0-0/src/app/api/mcp/prompts/list/route.ts
- v1-0-0/src/app/api/mcp/resources/list/route.ts
- v1-0-0/src/app/api/mcp/resources/read/route.ts
- v1-0-0/src/app/api/oauth/discover/route.ts
- v1-0-0/src/app/api/oauth/token/route.ts
- v1-0-0/src/app/oauth/callback/page.tsx
- v1-0-0/src/components/ChatTab.tsx
- v1-0-0/src/components/PromptsTab.tsx
- v1-0-0/src/components/ResourcesTab.tsx
- v1-0-0/src/components/ServersTab.tsx
- v1-0-0/src/components/ToolsTab.tsx
- v1-0-0/src/components/chat/chat-input.tsx
- v1-0-0/src/components/chat/markdown.tsx
- v1-0-0/src/components/chat/message.tsx
- v1-0-0/src/components/connection/ServerConnectionCard.tsx
- v1-0-0/src/hooks/use-chat.ts
- v1-0-0/src/hooks/useAppState.ts
- v1-0-0/src/lib/mcp-utils.ts
- v1-0-0/src/lib/oauth-discovery.ts
- v1-0-0/src/lib/oauth-security.ts
- v1-0-0/src/lib/pkce.ts
- v1-0-0/src/lib/types.ts
There were some bugs where if you only had the Anthropic key there, the chat was disabled. We want to change the logic so that it uses the first available key. 
> Clean up use chat 

- v1-0-0/src/components/chat/chat-helpers.ts
- v1-0-0/src/components/chat/chat-input.tsx
- v1-0-0/src/components/chat/model-selector.tsx
- v1-0-0/src/components/chat/provider-logo.tsx
See https://github.com/MCPJam/inspector/issues/287
> V1 0 0 playground model selector

- v1-0-0/src/components/TracingTab.tsx
- v1-0-0/src/components/logging/log-card.tsx
- v1-0-0/src/components/logging/log-level-badge.tsx
- v1-0-0/src/hooks/use-logger.ts
- v1-0-0/src/lib/date-utils.ts
> refactor(logging): refactor TracingTab component and introduce LogCard for better log entry display

- v1-0-0/src/components/ChatTab.tsx
- v1-0-0/src/hooks/use-chat.ts
- v1-0-0/src/lib/types.ts
_Brief description of your changes_
> fix token selection

- src/hooks/use-app-state.ts
- src/lib/types.ts
This PR addresses the issue reported in #301 by adding types for Oauth Tokens
**Changes Made**
Added types for Oauth Tokens and remove any type
> Add Types for  Oauth Tokens

- src/components/connection/ServerConnectionCard.tsx
What does this PR do?
resolves #304 
Adds the Refresh Token in the ServerConnectionCard component.
> Show Refresh Token

- client/index.html
https://github.com/MCPJam/inspector/issues/332
> feat: changed "MCP inspector" to "MCPJam Inspector" + svg

- client/src/components/ui/sonner.tsx
Added dismiss toast button in sonner.tsx corresponding to the issue ( Add dismiss toast button #355 ) that I've been assigned.
> feat(client): add dismiss toast button in sonner.tsx

- client/src/components/mcp-sidebar.tsx
**Description**
This PR resolves #348 
**Change Log**
Changes Icon of **Prompts** and **Resources**
> Changed icon for prompts and resources

- client/src/components/connection/AddServerModal.tsx
- client/src/components/connection/EditServerModal.tsx
Description
This PR resolves #356 
Change logs
Added Icon before title of Add and Edit MCP Server Modal
> Added Icon in Add & Edit MCP Server

- client/src/components/connection/EditServerModal.tsx
Added clientId logic from AddServerModal into EditServerModal as outlined in issue MCPJam/inspector#354.
>  feat(client): add client ID logic to EditServerModal.tsx

- client/src/components/SettingsTab.tsx
- client/src/components/setting/OllamaConfigDialog.tsx
- client/src/components/setting/OllamaTableRow.tsx
- client/src/components/setting/ProviderConfigDialog.tsx
- client/src/components/setting/ProviderTableRow.tsx
- client/src/components/setting/ProvidersTable.tsx
See #357
UI Design:
Switched from clunky cards to a clean, table with provider logos, status, API key, creation date, and actions.
Popup Dialogs:
Replaced inline editing with modals featuring provider logos, descriptions, and direct "Get API Key" links.Separate dialogs for API keys and Ollama URL.
Code Organization:
Refactored into 5 smaller subcomponents : Moved to a settings/ folder.
> Improve the UI for settings

- CLAUDE.md
- client/CLAUDE.md
- server/CLAUDE.md
> Added Cloude.md

- CLAUDE.md
- client/CLAUDE.md
- client/src/components/AuthTab.tsx
- client/src/components/ChatTab.tsx
- client/src/components/OAuthDebugCallback.tsx
- client/src/components/OAuthFlowProgress.tsx
- client/src/components/PromptsTab.tsx
- client/src/components/chat/chat-input.tsx
- client/src/components/connection/AddServerModal.tsx
- client/src/components/connection/EditServerModal.tsx
- client/src/components/mcp-sidebar.tsx
- client/src/components/sidebar/nav-main.tsx
- client/src/hooks/use-app-state.ts
- client/src/lib/debug-oauth-provider.ts
- client/src/lib/oauth-state-machine.ts
- server/CLAUDE.md
This PR adds a "Give feedback" button at the bottom of the sidebar that links users to the GitHub issues page.
Closes #386
If you notice any improvements that can be made regarding the button’s position, icon choice or others, please  let me know. I’m happy to make adjustments to ensure it fits seamlessly with the rest of the UI.
> Add feedback button

- client/src/components/connection/ServerConnectionCard.tsx
- package-lock.json
> Remove "Enabled" and "Disabled" text from server connection card  and also reduced the toggle size.

- client/package.json
- client/src/components/ToolsTab.tsx
This pull request improves handling of MCP-UI message types including `intent`, `notify`, `prompt`, `tool`, `link`. 
More info: https://mcpui.dev/guide/embeddable-ui
This also includes a small improvement to the response pane to allow larger UI elements to be rendered (previously the max height was too small for many MCP UI components).
> improve support for MCP-UI message types

- client/src/components/connection/ServerConnectionCard.tsx
Show the full server config instead of individual components of it. Make it copyable.
> Show the full server config

- client/src/components/ActiveServerSelector.tsx
- client/src/components/ChatTab.tsx
> Disable chat if there are no servers selected

- bin/start.js
- client/src/hooks/use-app-state.ts
- server/index.ts
The main changes in the PR include support for multiple CLI-provided MCP servers via an `mcp.json` file
Related PRs and Issues:
- #186 
- #118 
- #432 
This PR adds the ability to start the inspector with an `mcp.json` file:
```json
{
"mcpServers": {
"everything": {
"command": "npx",
"args": ["@modelcontextprotocol/server-everything"],
"env": {
"hello": "Hello MCP!"
}
},
"currency": {
"type": "sse",
"url": "https://currency-mcp.wesbos.com/sse",
"note": "For SSE connections, add this URL directly in Client"
},
"Sentry": {
"command": "npx",
"args": ["mcp-remote@latest", "https://mcp.sentry.dev/sse"]
}
}
}
```
Command:
```bash
npm run start -- --config mcp.json --server everything
```
Instead of filtering servers from the UI, this implementation:
1. **Shows ALL servers** from the config file …
> add MCP server configuration via config file (mcp.json) from cli

- client/src/components/connection/ServerModal.tsx
It will be a useful feature to let the users add custom headers (if required) by the server when connecting to a MCP server in addition to `Auth`  headers.
> feat: support custom headers in MCP server config

- client/src/components/ToolsTab.tsx
- client/src/components/tools/ToolsSidebar.tsx
> Add Search to Saved Requests

- client/src/App.tsx
- client/src/components/AuthTab.tsx
- client/src/components/EvalsTab.tsx
- client/src/components/PromptsTab.tsx
- client/src/components/ResourcesTab.tsx
- client/src/components/ToolsTab.tsx
- client/src/components/ui/empty-state.tsx
- package-lock.json
- Created reusable `EmptyState` component for consistent empty state design
- Improved mobile responsiveness across all tabs
- Removed redundant helper text for cleaner UI
- Optimized text display for different screen sizes
- Implemented in: ToolsTab, ResourcesTab, AuthTab, PromptsTab, EvalsTab
> Refactor tabs to use EmptyState component for better UX

- Dockerfile
- client/src/components/ui/empty-state.tsx
- server/index.ts
Fixes #526 and also builds on top of https://github.com/MCPJam/inspector/pull/527
> docker: update Dockerfile for production build and asset serving

- client/src/components/ChatTab.tsx
> Chat UX improvements
