MCPJam/inspector

client/src/App.tsx
This pull request introduces an auto-connect feature upon client creation and refines the connection logic for various client management scenarios.
Key Changes:
Auto-Connect on Client Creation: When a user creates a single new client, the application now automatically establishes a connection to that client, streamlining the user workflow.
Selective Auto-Connection for Multi-Client Import: The auto-connect feature is disabled by default when importing multiple clients at once. This prevents a flurry of connection attempts and allows the user to manually connect to the desired client.
Refactored Connection Logic:
The handleAddServer function was updated to include an autoConnect option, centralizing the connection logic.
The onOAuthConnect callback was simplified to leverage the new …
=> Auto connect on create

client/src/components/DynamicJsonForm.tsx
Modify the useEffect to ensure it updates the component's state with the loaded request's data, even in JSON mode. This might cause the cursor to jump during manual JSON editing, but it will fix the critical bug of not loading and saving array parameters correctly.
Closes #83
=> Save array requests

cli/package.json, client/package.json, client/src/App.tsx, client/src/components/DynamicJsonForm.tsx, client/src/components/ElicitationModal.tsx, client/src/hooks/useConnectionState.ts, client/src/hooks/useMCPOperations.ts, client/src/mcpjamAgent.ts, client/src/mcpjamClient.ts, client/src/utils/jsonUtils.ts, client/src/utils/mcpHelpers.ts, package-lock.json, package.json, server/package.json
Inspired by https://github.com/modelcontextprotocol/inspector/pull/535. All credits to @QuantGeekDev 
https://github.com/user-attachments/assets/c4b8403a-b224-46b4-be80-f3affa920103
=> Add Elicitation support

client/src/App.tsx, client/src/components/ElicitationModal.tsx, client/src/hooks/useConnectionState.ts, client/src/mcpjamAgent.ts
Fix types for elicitation: 
Before: Use of `any` type everywhere 
After: Enforce types
=> Fix types for elicitation 

client/src/components/ToolCallMessage.tsx, client/src/lib/chatLoop.ts, client/src/mcpjamAgent.ts, client/src/mcpjamClient.ts, client/src/utils/toolCallHelpers.ts
---
name: Pull Request
about: Create a pull request to help us improve
title: ""
labels: ""
assignees: ""
---
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
_A brief description of the motivation behind this PR. Link to any related issues._
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
_If your change is a breaking change, please describe the impact and migration path for existing users._
_Add any other context about the problem here._
=> Show tool result

client/src/components/chat/ToolCallApproval.tsx
This PR updates the color scheme of the Tool Call Approval component (ToolCallApproval.tsx) by replacing the amber/orange colors with a more neutral blue-gray (slate) palette using TailwindCSS.
=> Replace amber colors with blue-gray in ToolCallApproval (#156)

cli/src/cli.ts, client/bin/client.js, client/bin/start.js
Resolves #144 
- Add clickable URLs in cli.ts console output using ANSI escape sequences
- Add clickable URLs in client.js server status messages
- Add clickable URLs in start.js console output
- Improve user experience by making localhost URLs interactive in terminal
This change makes it easier for users to open the inspector interface by clicking the URLs directly in their terminal instead of copying and pasting.
=> feat(cli): add clickable console URLs

client/src/components/ClientFormSection.tsx
Improves the client name validation UX by only showing validation errors after user interaction with the field. This builds on PR #160 by addressing the initial error state that could confuse users.
Changes made:
- Added `isNameTouched `state to track field interaction
- Modified validation logic to only show errors after field interaction
- Added `onBlur` handler to detect when user leaves the name input field
- Maintains required field validation while providing better user feedback timing
- Marks client name field as required with * in ClientFormSection
Open the client creation form
1. Verify the name field starts with no error state
2. Click into the name field and then click away (blur) - should show error
3. Type a name and verify error disappears
4. Delete the name and click away - …
=> Delayed client name validation

client/src/components/ToolsTab.tsx
- Replace wrench emoji with Hammer icon from lucide-react in tooltab.tsx
- Ensure consistent icon usage between tool displays and navigation tabs
Fixes #171
This PR standardizes the icon usage across the MCPJam Inspector UI by replacing the wrench emoji with a proper Hammer icon from lucide-react in the Tools tab. This ensures visual consistency between the navigation tabs and tool displays, following the established design pattern used throughout the application.
1. Navigate to the Tools tab
2. Verify that the tab icon now shows a Hammer icon (from lucide-react) instead of the wrench emoji
3. Compare the Tools tab icon with other tab icons to ensure consistent styling and sizing
4. Check that tool displays throughout the app use matching iconography
=> fix: standardize tool icons to match tab design pattern

client/src/components/History.tsx, client/src/components/TabbedHistoryPanel.tsx, client/src/components/ToolsTab.tsx, package-lock.json, package.json
Refined collapsed pane UI with soft gradient background and hover‑lift shadow
Expanded collapsed height (80px) for better click target and spacing
Added smooth chevron flip animation on expand/collapse
Displayed “Last action” subtitle (e.g. “Last req: 2m ago”) for instant context
Introduced mini “pill” bars to visually encode request vs. log counts
Kept and styled the drag‑to‑resize handle (Grip icon), including hover feedback
Retained all existing expand/resize/keyboard‑shortcut functionality unchanged
=> (Creative) Improve the History pane UI #167

client/src/components/TabbedHistoryPanel.tsx
Resolves: https://github.com/MCPJam/inspector/issues/187
- Introduced a button to copy client logs to the clipboard.
- Implemented toast notifications for successful and failed copy actions.
- Updated the UI to include the new CopyLogsButton component in the logs tab.
Copied content: 
```
[2025-07-07T04:16:19.835Z] DEBUG: Checking MCP proxy server health
[2025-07-07T04:16:19.854Z] DEBUG: MCP proxy server health check passed
[2025-07-07T04:16:19.855Z] INFO: Attempting to connect to MCP server (attempt 1/2)
[2025-07-07T04:16:19.855Z] INFO: Connecting to MCP server via stdio: npx
[2025-07-07T04:16:21.711Z] INFO: Successfully connected to MCP server via stdio
[2025-07-07T04:16:21.712Z] DEBUG: Server capabilities retrieved: {"resources":{},"tools":{"listChanged":true}} …
```
=> feat(client): add copy logs functionality to TabbedHistoryPanel

client/src/components/ClientLogsTab.tsx
Only shows copy log icon (found in logs) when user hovers over component
=> Fix: Copy icon only shows up on hover [#202]

client/src/components/Sidebar/ConnectionItem.tsx, client/src/components/Sidebar/connectionHelpers.tsx, client/src/utils/stringUtil.ts
Resolve: https://github.com/MCPJam/inspector/issues/212
* Provide 2 solutions to handle the issue:
* Add a `StringUtil` and a shorten string function to allow the truncation of URL
* But the truncation is still not a good idea when any of `connection.config.args` is too long -> allowing them to wrap to the next line using the CSS `break-all` class (I know it's a bit hard to understand, I can explain more if needed)
1. Create a connection with a long command and multiple arguments
2. Verify the command text wraps to the next line in the sidebar
3. Check that URLs are still shortened appropriately
4. Test at different sidebar widths to ensure proper wrapping
=> Shorten string

client/src/components/chat/ToolSelector.tsx
This pull request adds the ability to collapse and expand the list of tools for each server, making it easier for users to navigate.
Closes #151 
Navigate to the `Chat` tab and click the `Tools` button. A chevron icon should appear next to each server, allowing you to toggle the visibility of its tools.
=> Add button to collapse/expand server tools

client/src/components/OAuthCallback.tsx, client/src/hooks/app/useOAuthHandlers.ts, client/src/lib/types/constants.ts, client/src/lib/utils/auth/auth.ts, client/src/lib/utils/mcp/mcpjamClient.ts
Before, auth with streamable http was broken. This was because we hard coded the OAuth flow to return a hard coded "sse" route, when it should be `streamable-http`. We are able to persist the connection type via browser storage. 
Test that https://huggingface.co/mcp?login now works
=> Fix auth on streamable HTTP

client/src/hooks/app/useAppEffects.ts
For more information:
https://github.com/MCPJam/inspector/issues/260
=> feat: add option to initialize mcp-connection with streamable http

v1-0-0/src/app/page.tsx
Temporarily removes the profile icon (AccountSwitcher) from the upper right corner of the header
as requested in issue #264.
1. Run the v1.0.0 application (`cd v1-0-0 && npm run dev`)
2. Navigate to any page
3. Verify the profile icon is no longer visible in the upper right corner
4. Only the theme switcher should remain in the header
=> fix(v1.0.0): temporarily remove profile icon in header

v1-0-0/src/components/connection/ServerConnectionCard.tsx
- Added logic to extract and display manual Bearer tokens from Authorization headers
- Implemented prioritization: OAuth tokens take precedence when both auth methods exist
- Added "(Manual)" label to distinguish manual tokens from OAuth tokens
- Included copy functionality for manual Bearer tokens
- Updated expandable content conditions to show manual tokens when no OAuth is present
=> fix(v1.0.0): display manual Bearer tokens in server connection cards

client/src/components/settings/ProviderCard.tsx
Improved spacing between logo and title in ProviderCard component.
- Added `gap-1` in the header flex container.
- This addresses the spacing issue more effectively than adding left padding to the title.
- ✅ Tested in light mode.
- ✅ Tested in dark mode.
=> fix: improve spacing between logo and title in ProviderCard (fixes #245)

SECURITY.md, src/hooks/use-app-state.ts, src/lib/mcp-oauth.ts
The refresh tokens are never used to get new access tokens. In this PR we make that happen. Users can get a new access token if they hit refresh.
=> Use refresh token to get new auth token 

claude-code-prompts/edit_server_modal_07_29.md, src/app/page.tsx, src/components/ServersTab.tsx, src/components/connection/AddServerModal.tsx, src/components/connection/EditServerModal.tsx, src/components/connection/ServerConnectionCard.tsx, src/hooks/use-app-state.ts, src/lib/mcp-oauth.ts, src/lib/types.ts
Create the ability to edit a server config. Editing a server config will open the edit server modal. The edit server modal will have all the fields of the server its editing already filled out. Allow the user to edit and save the new configuration.
Create a component `EditServerModal` in `src/components/connection/EditServerModal.tsx`. This modal should have the same structure as `AddServerModal`, but it should be able to take in a server config and pre-fill the form. Allow the user to edit the form in the modal.
On submit, delete the original server and connect to an MCP with the new config.
Create a button right below the "Reconnect" option in the component `ServerConnectionCard.tsx` called "edit". Clicking on the button will open up the `EditServerModal`.
Propose how to do this before …
=> Add the ability to edit server configs 

.gitignore, bin/start.js, client/package-lock.json, client/src/hooks/use-app-state.ts, package-lock.json, server/index.ts, server/package-lock.json
Enables users to automatically connect to MCP servers via CLI arguments.
Users can now run:
```
npx @mcpjam/inspector node build/index.js arg1 arg2
```
The server will automatically connect without manual setup, matching Anthropic's MCP Inspector behavior.
Changes
- Add CLI argument parsing in bin/start.js
- Add auto-connect logic in client hook
- Support both development and production modes
- Add API endpoint for development mode config
Closes #337
=> Feat: add CLI MCP server auto-connect support

client/src/components/connection/AddServerModal.tsx, client/src/components/connection/EditServerModal.tsx
**Description**
This pull request solves issue #359 
**Change Logs** 
This PR updates the text of the Connection Type dropdown from "HTTP" to "HTTP/SSE" in both the Add and Edit MCP Server modals.
=> Changed Dropdown from HTTP to HTTP/SSE

client/package.json, client/vite.config.ts
` @mcp-ui/client` package includes React 18.3.1 while the main project uses React 19.1.0, causing import resolution conflicts. Please use `npm run dev:clean ` to clear vite cache
=> Fix vite config

client/src/components/chat/message.tsx, client/src/components/chat/model-selector.tsx, client/src/lib/chat-utils.ts
Implement nested submenu pattern for model selection with provider grouping
- Replace flat model list with provider-based navigation
- Add DropdownMenuSub components for right-side submenu display
- Group models by provider (Anthropic, OpenAI, DeepSeek, Ollama)
- Implement hover/click triggers to open provider submenus
- Add collision detection to prevent submenus from going off-screen
- Display model counts for each provider in main menu
- Maintain current model selection indicator across submenus
Previous View : 
Updated View :
=> Grouped all the models together by their providers

server/index.ts, server/routes/mcp/connect.ts, server/routes/mcp/prompts.ts, server/routes/mcp/resources.ts, server/routes/mcp/servers.ts, server/routes/mcp/tools.ts, server/types/hono.ts
We want to use `c.mcpClientManager`
=> Clean up use of global variables in Hono

client/src/hooks/use-app-state.ts, package.json
The fix ensures that loaded configs have their string URLs converted back to URL objects before being used
=> Convert to url objects

vite.renderer.config.mts
1. fix the electron api 404 error
2. but `/api/mcp-cli-config` still 404, because it's not defined in `createHonoApp` (which used in electron main)
=> fix(electron): set the renderer vite hmr server proxy the hono

evals-cli/bin/mcpjam.js
On Windows using the cli mode
```powershell
mcpjam evals run --tests mcp-tests.json --environment mcp-environment.json --llms mcp-llms.json
```
this throws Error:
Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
=> Update mcpjam.js to also support paths on windows

README.md
Updates the Star History chart in the README to display the repository stats
fix #573
=> Add star history section to README
